name: 'OpenAPI Client Generator Action'
description: 'Generates OpenAPI documentation using OpenAPI Generator'
author: 'diegoara96'
inputs:
  url:
    description: 'The URL of the backend API to obtain the OpenAPI specification (optional).'
    required: false
  spec-file:
    description: 'The JSON file containing the OpenAPI specification (optional).'
    required: false
  output-dir:
    description: 'The directory where the generated documentation will be saved.'
    required: false
    default: './docs'
  generator:
    description: 'The generator to be used for generating the documentation (html, html2, markdown, etc.).'
    required: false
    default: 'html2'  # Default to 'html2' if no value is provided
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.url }}
    - ${{ inputs.spec-file }}
    - ${{ inputs.output-dir }}
    - ${{ inputs.generator }}
